---
title: "Modelling help"
author: "James Thompson - 21011195"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
load("overplotting.rData")
```

Here is the data in a table it isnt very long

```{r}
tibble(overplotting)
```
These are the plots which show how the figure dimension is linear with number yet size is curved.

```{r}
figDim = ggplot(overplotting, aes(figDim, number)) +
  geom_point(aes(colour = as.factor(size)))
figDim

size = ggplot(overplotting, aes(size, number)) +
  geom_point(aes(colour=as.factor(figDim)))
size
```

This is the simple log transformation plot.
It is only supposed to work up to shape size of 20 or so.
However I think it still doesnt do a very good job of predicting do you have any ideas?


```{r}
m.figInterSize = lm(number ~ figDim * log(size) - 1, data=overplotting)
summary(m.figInterSize)

## Not needed as wont help understand
# sizeSeq = seq(0.5,50,length.out=55)
# plot(sizeSeq, predict(m.figInterSize, data.frame(size=sizeSeq, figDim= 1)),
#      ylim=c(-30,300))
# for (fig in 1:15) {
#   figConstant = predict(m.figInterSize, data.frame(size=sizeSeq, figDim= fig))
#   lines(sizeSeq, figConstant)
# }
```