---
title: "quickBuild"
author: "James Thompson - 21011195"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
overplotting = data.frame(matrix(ncol = 3, nrow = 0))
colnames(overplotting) = c("figDim", "number", "size")

getGridDF <- function(N) {
  seq = seq(1,100, length.out=N)
  x= rep(seq, each=N)
  y = rep(seq, N)
  data.frame(x,y)
}

plotGraph <- function(N, size) {
  df = getGridDF(N)
  plot = ggplot(df, aes(x, y)) + 
    geom_point(size=size)
  return(plot)
}
```

### Largest figure

```{r fig.dim=c(15,15)}
# Smallest points
N = 420
size = 0.5
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)

# Default
N =260
size = 1.5
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)

# small Points
N = 139
size = 3
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)

# Medium
N = 83
size = 5.05
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)

# Large
N = 59
size = 7.5
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)


# Extra large points
N = 45
size = 10
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)

# Super large
N = 23
size = 19.9
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)

# Silly big for models
N = 10
size = 50
plotGraph(N, size)
overplotting[nrow(overplotting)+1,] <- c(dev.size()[1], N, size)
```